# Change these first
owner: octocat145 # Your GitHub organization or username, where this repository lives
repo: supreme-spoon # The name of this repository

sites:
  - name: 14chan
    url: https://14chan.org/
    type: globalping
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
  - name: 1500chan
    url: https://1500chan.org/
    type: globalping
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
  - name: 27chan
    url: https://27chan.org/
    type: globalping
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
  - name: Anões
    url: https://anoes.net/
    type: globalping
    location: Brazil
  - name: Azumangachan
    url: https://azumangachan.rf.gd/
    type: globalping
  - name: Goiaba
    url: https://goiaba.fi/
    type: globalping
  - name: gavetachan
    url: https://gavetachan.org/
    type: globalping
  - name: Lusochan
    url: https://lusochan.net/
    type: globalping
    location: Portugal
  - name: Magalichan
    url: https://magalichan.com/
    type: globalping
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
  - name: mokoichannel
    url: https://mokoich.net/
    type: globalping
  - name: ptちゃん
    url: https://ptchan.org/
    type: globalping
  - name: Qchan
    url: https://qchan.org/
    type: globalping
  - name: Reinchan
    url: https://reinchan.org/
    type: globalping
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
  - name: tchan
    url: https://tchan.lol/
    type: globalping
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404

skipDeleteIssues: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: chanuptime.qzz.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/octocat145/supreme-spoon/refs/heads/master/CPLP_logo.svg
  name: chan Uptime
  introTitle: "**chan Uptime** é um [Monitor de Tempo de Atividade](https://minacriativa.com.br/glossario/o-que-e-uptime-tempo-de-atividade/) para [chans/*boards](https://internetsparaleigos.wordpress.com/2010/05/06/2ch-e-futaba/) [lusófonos](https://pt.wikipedia.org/wiki/Lusofonia)."
  introMessage: "Status operacional e saúde dos [chans/*boards](https://internetsparaleigos.wordpress.com/2010/05/06/2ch-e-futaba/) [lusófonos](https://pt.wikipedia.org/wiki/Lusofonia) em tempo real."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night
  favicon: https://raw.githubusercontent.com/octocat145/supreme-spoon/refs/heads/master/antennabars.png

i18n:
  activeIncidents: Incidentes Ativos
  allSystemsOperational: Todos os sistemas estão operacionais
  incidentReport: "Relatório do incidente #$NUMBER →"
  activeIncidentSummary: Iniciado em $DATE com $POSTS publicações
  incidentTitle: Detalhes do Incidente $NUMBER
  incidentFixed: Resolvido
  incidentOngoing: Em andamento
  incidentOpenedAt: Iniciado em
  incidentClosedAt: Encerrado em
  incidentViewOnGitHub: Visualizar e Inscrever-se no GitHub
  incidentCommentSummary: Publicado em $DATE por $AUTHOR
  incidentBack: ← Retornar à lista completa de Incidentes
  pastIncidents: Incidentes Anteriores
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS publicações
  liveStatus: Status Atual
  overallUptime: "Tempo de atividade geral: $UPTIME"
  overallUptimeTitle: Tempo de atividade geral
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Tempo médio de resposta
  sevelDayResponseTime: Tempo de resposta de 7 dias
  responseTimeMs: Tempo de resposta (ms)
  ms: ms
  loading: Carregando
  up: No ar
  down: Fora do ar
  degraded: Degradado
  footer: Este site é de [Código Aberto](https://github.com/octocat145/supreme-spoon/) com a tecnologia de [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Limite de requisições excedido
  errorTitle: Erro
  errorIntro: Ocorreu um erro ao tentar obter os detalhes de status mais recentes.
  errorText: Você pode tentar novamente em alguns instantes.
  errorHome: Ir para a página inicial
  pastScheduledMaintenance: Manutenções Passadas
  scheduledMaintenance: Manutenção Agendada
  scheduledMaintenanceSummaryStarted: Iniciada em $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia em $DATE por $DURATION minutos
  startedAt: Iniciada em
  startsAt: Inicia em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Concluído
  incidentScheduled: Agendado
  duration24H: 24h
  duration7D: 7 dias
  duration30D: 30 dias
  duration1Y: 1 ano
  durationAll: Tudo

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
